// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.version_code = 8
    ext.version_name = '1.0.7'
    ext.versions = [
            'min_sdk'              : 21,
            'target_sdk'           : 35,
            'compile_sdk'          : 35,
            'build_tool'           : '30.0.2',
            'kotlin'               : '1.6.21',
            'constraint_layout'    : '2.2.1',
            'lifecycle'            : '2.4.1',
            'lifecycle_extensions' : '2.2.0',
            'room'                 : '2.4.1',
            'koin'                 : '3.2.3',
            'firebase_bom'         : "27.1.0"
    ]
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath 'com.google.gms:google-services:4.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$versions.kotlin"
        classpath 'com.google.firebase:firebase-crashlytics-gradle:3.0.3'
        // Secret API Key
        classpath "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:2.0.1"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
